### ISSUE TITLE
Low Volume Hitsound Check Inefficiency

### ISSUE THREAD

**Issue by Alchyr** [Naxesss/MapsetChecks#4]
The check checks/all modes/hit sounds/CheckMuted.cs may take an excessive amount of time to complete on maps with a high amount of timing points and objects.

It's not at all noticable in most cases, but it can take quite a bit of time in more... extreme cases.

https://osu.ppy.sh/beatmapsets/978163 - My map that I noticed the delay on. Very much not what I would consider a common use case, but still something that might occur. (1228 timing points, 7007 objects at time of writing)

Note: This is based on what is displayed during the Check process

**Comment by Naxesss** [comment]
I believe your unedited message had the correct lead, the GetTimingLine function was iterating through each timing line from the beginning for each hit object. Additionally, the GetTimestamp function used in the error message was calling GetPrevHitObject to determine the combo number. This function uses the same logic as GetTimingLine, and as such causes the same issue.

Storing the hit object index and using it to (continue) traversing the object list for both cases turns out to be much more efficient. Will push a fix soon.
